### ISSUE TITLE
1.0.0-beta

### ISSUE THREAD

**Issue by vardius** [vardius/peer-cdn#11]
release beta after milestone steps are done
For more info chcek milestone decs

# todo
- [x] allow to provide custom cache names
- [x] fix message channel closure
- [x] create better socket server with ability to extend
- [x] update docs and readme
